# Generated by Django 5.0.3 on 2024-03-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("milo_cotiza", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingreso_equipos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Cliente", models.CharField(max_length=100)),
            ],
        ),
    ]
