# Generated by Django 5.0.3 on 2024-03-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Models_Tickets",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
